<?php

add_filter( 'better-framework/product-pages/install-plugin/config', 'publisher_plugin_installer_config' );

/**
 * Ads exclusive and public plugins to plugin installer
 *
 * @param $plugins
 *
 * @return mixed
 */
function publisher_plugin_installer_config( $plugins ) {

	$plugins['js_composer']                           = array(
		'name'                   => __( 'Visual Composer', 'publisher' ),
		'slug'                   => 'js_composer',
		'required'               => TRUE,
		'description'            => __( '#1 page builder plugin for WordPress - take full control over your site.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/js_composer.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'WPBakery',
		'author_uri'             => 'http://wpbakery.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-adsmanager']                     = array(
		'name'                   => __( 'Better Ads Manager', 'publisher' ),
		'slug'                   => 'better-adsmanager',
		'required'               => FALSE,
		'description'            => __( 'Advanced ads manager with huge options + ads blockers fallback.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-adsmanager.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-amp']                            = array(
		'name'                   => __( 'Better AMP', 'publisher' ),
		'slug'                   => 'better-amp',
		'required'               => FALSE,
		'description'            => __( 'Enables your site to load 4x faster in mobiles!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-amp.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-social-counter']                 = array(
		'name'                   => __( 'Better Social Counter', 'publisher' ),
		'slug'                   => 'better-social-counter',
		'required'               => FALSE,
		'description'            => __( 'Complete solution for showing social networks stats on site.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-social-counter.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['wp-migrator-client']                    = array(
		'name'                   => __( 'Publisher Migrator', 'publisher' ),
		'slug'                   => 'wp-migrator-client',
		'required'               => FALSE,
		'description'            => __( 'Switch to Publisher without losing data or shortcodes', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/publisher-migrator.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
	);
	$plugins['newsletter-pack-pro']                   = array(
		'name'                   => __( 'Newsletter Pack - Pro', 'publisher' ),
		'slug'                   => 'newsletter-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'Show and manage newsletters easily.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/newsletter-pack.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,

	);
	$plugins['blockquote-pack-pro']                   = array(
		'name'                   => __( 'Blockquote Pack - Pro', 'publisher' ),
		'slug'                   => 'blockquote-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'The best way to show quote and citation!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/blockquote-pack.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['smart-lists-pack-pro']                  = array(
		'name'                   => __( 'Smart Lists Pack - Pro', 'publisher' ),
		'slug'                   => 'smart-lists-pack-pro',
		'required'               => FALSE,
		'description'            => __( 'The best way to show lists and paged posts!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/smart-lists-pack.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-weather']                        = array(
		'name'                   => __( 'Better Weather', 'publisher' ),
		'slug'                   => 'better-weather',
		'required'               => FALSE,
		'description'            => __( 'The best way to show weather to the world.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-weather.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-post-views']                     = array(
		'name'         => __( 'Better Post Views', 'publisher' ),
		'slug'         => 'better-post-views',
		'required'     => FALSE,
		'description'  => __( 'Count post views per day and week and show 7 days popular posts.', 'publisher' ),
		'thumbnail'    => bf_get_theme_uri( 'includes/plugins/images/better-post-views.png' ),
		'type'         => 'bundled',
		'author'       => 'Better Studio',
		'author_uri'   => 'http://betterstudio.com',
		'is_exclusive' => TRUE,
	);
	$plugins['better-reviews']                        = array(
		'name'         => __( 'Better Reviews', 'publisher' ),
		'slug'         => 'better-reviews',
		'required'     => FALSE,
		'description'  => __( 'Review products in 3 type with stylish design.', 'publisher' ),
		'thumbnail'    => bf_get_theme_uri( 'includes/plugins/images/better-reviews.png' ),
		'type'         => 'bundled',
		'author'       => 'Better Studio',
		'author_uri'   => 'http://betterstudio.com',
		'is_exclusive' => TRUE,

	);
	$plugins['financial-pack-pro']                    = array(
		'name'                   => __( 'Financial Pack - Pro', 'publisher' ),
		'slug'                   => 'financial-pack-pro',
		'required'               => FALSE,
		'description'            => sprintf( __( 'The best and complete financial widgets and shortcodes', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/financial-pack-pro.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'BetterStudio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['fb-instant-articles']                   = array(
		'name'                   => __( 'Facebook Instant Articles', 'publisher' ),
		'slug'                   => 'fb-instant-articles',
		'required'               => FALSE,
		'description'            => __( 'Facebook Instant Articles support.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/fia.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Automattic, Dekode, Facebook',
		'author_uri'             => 'https://vip.wordpress.com/plugins/instant-articles/',
	);
	$plugins['better-wp-embedder']                    = array(
		'name'                   => __( 'Embed Any Document', 'publisher' ),
		'slug'                   => 'better-wp-embedder',
		'required'               => FALSE,
		'description'            => __( 'Embed 40+ document type by using Better WP Embedder plugin.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-wp-embedder.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => FALSE,
		'reload_after_uninstall' => FALSE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-playlist']                       = array(
		'name'        => __( 'Better Playlist', 'publisher' ),
		'slug'        => 'better-playlist',
		'required'    => FALSE,
		'description' => __( 'The best way to Youtube playlist\'s and Vimeo album\'s in WordPress', 'publisher' ),
		'thumbnail'   => bf_get_theme_uri( 'includes/plugins/images/better-playlist.png' ),
		'type'        => 'bundled',
		'author'      => 'Better Studio',
		'author_uri'  => 'http://betterstudio.com',
		'is_premium'  => TRUE,
	);
	$plugins['better-google-custom-search']           = array(
		'name'                   => __( 'Better Google Custom Search', 'publisher' ),
		'slug'                   => 'better-google-custom-search',
		'required'               => FALSE,
		'description'            => __( 'Replace the default WordPress search engine with search powered by Google.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-google-custom-search.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-facebook-chat']                  = array(
		'name'                   => __( 'Better Facebook Chat', 'publisher' ),
		'slug'                   => 'better-facebook-chat',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Integrate Facebook Messenger experience directly into your website.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-facebook-chat.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'BetterStudio',
		'author_uri'             => 'http://betterstudio.com',
		'is_premium'             => TRUE,
	);
	$plugins['better-disqus-comments']                = array(
		'name'                   => __( 'Better Disqus Comments', 'publisher' ),
		'slug'                   => 'better-disqus-comments',
		'required'               => FALSE,
		'description'            => __( 'Use DISQUS comments for theme with this plugin.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-disqus-comments.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
	);
	$plugins['better-facebook-comments']              = array(
		'name'                   => __( 'Better Facebook Comments', 'publisher' ),
		'slug'                   => 'better-facebook-comments',
		'required'               => FALSE,
		'description'            => __( 'Use Facebook comments for theme with this plugin.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/better-facebook-comments.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Better Studio',
		'author_uri'             => 'http://betterstudio.com',
		'is_exclusive'           => TRUE,
	);
	$plugins['custom-sidebars']                       = array(
		'name'                   => __( 'Custom sidebars', 'publisher' ),
		'slug'                   => 'custom-sidebars',
		'required'               => FALSE,
		'description'            => __( 'Create and customize sidebars for pages with easy user interface.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/custom-sidebars.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'WPMU DEV',
		'author_uri'             => 'http://premium.wpmudev.org',
		'is_compatible'          => TRUE,
	);
	$plugins['wordpress-social-login']                = array(
		'name'                   => __( 'Social Login', 'publisher' ),
		'slug'                   => 'wordpress-social-login',
		'required'               => FALSE,
		'description'            => __( 'Allow your visitors to comment and login with social networks.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/wordpress-social-login.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Miled',
		'author_uri'             => 'http://github.com/miled',
		'is_compatible'          => TRUE,
	);
	$plugins['contact-form-7']                        = array(
		'name'                   => __( 'Contact Form 7', 'publisher' ),
		'slug'                   => 'contact-form-7',
		'required'               => FALSE,
		'description'            => __( 'Just another contact form plugin. Simple but flexible.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/contact-form-7.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Takayuki Miyoshi',
		'author_uri'             => 'http://ideasilo.wordpress.com',
		'is_compatible'          => TRUE,
	);
	$plugins['onesignal-free-web-push-notifications'] = array(
		'name'                   => __( 'Push Notifications', 'publisher' ),
		'slug'                   => 'onesignal-free-web-push-notifications',
		'required'               => FALSE,
		'description'            => sprintf( __( 'OneSignal – Free Web Push Notifications is a complete push notification solution for WordPress', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/onesignal.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'OneSignal',
		'author_uri'             => 'https://onesignal.com/',
		'is_compatible'          => TRUE,
	);
	$plugins['real3d-flipbook']                       = array(
		'name'                   => __( 'Real 3D FlipBook', 'publisher' ),
		'slug'                   => 'real3d-flipbook',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Premium Responsive Real 3D FlipBook', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/real3d-flipbook.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Creative Interactive Media',
		'author_uri'             => 'http://codecanyon.net/user/creativeinteractivemedia/portfolio?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['convertplug']                           = array(
		'name'                   => __( 'Convert Plug', 'publisher' ),
		'slug'                   => 'convertplug',
		'required'               => FALSE,
		'description'            => sprintf( __( 'The easiest WordPress plugin to convert website traffic into leads', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/convertplug.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Brainstorm Force',
		'author_uri'             => 'https://codecanyon.net/item/popup-plugin-for-wordpress-convertplug/14058953?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['Ultimate_VC_Addons']                    = array(
		'name'                   => __( 'Ultimate Addons for Visual Composer', 'publisher' ),
		'slug'                   => 'Ultimate_VC_Addons',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Extend WPBakery Page Builder and add more power to it!', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/Ultimate_VC_Addons.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Brainstorm Force',
		'author_uri'             => 'https://codecanyon.net/item/ultimate-addons-for-visual-composer/6892199?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['theia-smart-thumbnails']                = array(
		'name'                   => __( 'Smart Thumbnails', 'publisher' ),
		'slug'                   => 'theia-smart-thumbnails',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Gain full control over your thumbnails by customizing the cropping zone for each one of them.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/theia-smart-thumbnails.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'WeCodePixels',
		'author_uri'             => 'https://codecanyon.net/item/theia-smart-thumbnails-for-wordpress/3160252?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['advanced-custom-fields-pro']            = array(
		'name'                   => __( 'Advanced Custom Fields Pro', 'publisher' ),
		'slug'                   => 'advanced-custom-fields-pro',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Customise WordPress with powerful, professional and intuitive fields.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/advanced-custom-fields-pro.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Elliot Condon',
		'author_uri'             => 'https://www.advancedcustomfields.com/',
		'is_premium'             => TRUE,
	);
	$plugins['totalpoll']                             = array(
		'name'                   => __( 'TotalPoll Pro', 'publisher' ),
		'slug'                   => 'totalpoll',
		'required'               => FALSE,
		'description'            => sprintf( __( 'TotalPoll is a powerful WordPress plugin that lets you create and integrate polls easily. It provides several options and features to enable you have full control over the polls, and has been made very easier for you to use.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/totalpoll.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'MisqTech',
		'author_uri'             => 'https://codecanyon.net/item/totalpoll-pro-responsive-wordpress-poll-plugin/7647147?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['masterslider']                          = array(
		'name'                   => __( 'Master Slider Pro', 'publisher' ),
		'slug'                   => 'masterslider',
		'required'               => FALSE,
		'description'            => sprintf( __( 'HTML5 WordPress slider plugin with layer and Touch Swipe Navigation.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/masterslider.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Averta',
		'author_uri'             => 'https://codecanyon.net/item/master-slider-wordpress-responsive-touch-slider/7467925?ref=Better-Studio',
		'is_premium'             => TRUE,
	);
	$plugins['revslider']                             = array(
		'name'                   => __( 'Slider Revolution', 'publisher' ),
		'slug'                   => 'revslider',
		'required'               => FALSE,
		'description'            => __( '#1 WordPress slider plugin ever created and used!', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/revslider.png' ),
		'type'                   => 'bundled',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'ThemePunch',
		'author_uri'             => 'http://themepunch.com',
		'is_premium'             => TRUE,
	);
	$plugins['woocommerce']                           = array(
		'name'                   => __( 'WooCommerce', 'publisher' ),
		'slug'                   => 'woocommerce',
		'required'               => FALSE,
		'description'            => __( 'Powerful and extendable eCommerce plugin that helps you sell anything.', 'publisher' ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/woocommerce.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'Automattic',
		'author_uri'             => 'http://woocommerce.com',
		'is_compatible'          => TRUE,
	);
	$plugins['bbpress']                               = array(
		'name'                   => __( 'bbPress', 'publisher' ),
		'slug'                   => 'bbpress',
		'required'               => FALSE,
		'description'            => sprintf( __( 'Create forums! %s is fully compatible with bbPress.', 'publisher' ), publisher_white_label_get_option( 'publisher' ) ),
		'thumbnail'              => bf_get_theme_uri( 'includes/plugins/images/bbpress.png' ),
		'type'                   => 'global',
		'reload_after_install'   => TRUE,
		'reload_after_uninstall' => TRUE,
		'author'                 => 'The bbPress Community',
		'author_uri'             => 'http://bbpress.org',
		'is_compatible'          => TRUE,
	);

	return $plugins;
}
